<a href="https://colab.research.google.com/github/prodramp/python-projects/blob/main/deeplearning/cnn/Simple_CNN_convolution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
from tensorflow.keras.layers import Input, Dense, Conv2D, MaxPooling2D, Flatten, Dropout 
from keras.models import Sequential, Model

In [2]:
model_cnn = Sequential([
    Conv2D(64, 3, input_shape=(128,128,1), use_bias=True ),
    MaxPooling2D(pool_size=4),
    Flatten(),
    Dropout(0.5),
    Dense(1, activation='softmax')
])

In [3]:
model_cnn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 126, 126, 64)      640       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 31, 31, 64)       0         
 )                                                               
                                                                 
 flatten (Flatten)           (None, 61504)             0         
                                                                 
 dropout (Dropout)           (None, 61504)             0         
                                                                 
 dense (Dense)               (None, 1)                 61505     
                                                                 
Total params: 62,145
Trainable params: 62,145
Non-trainable params: 0
____________________________________________________

In [41]:
model_cnn.save('simple_cnn.h5')

In [4]:
input_shape = (4, 28, 28, 3)

In [5]:
x = tf.random.normal(input_shape)

In [6]:
x.shape

TensorShape([4, 28, 28, 3])

In [7]:
input_shape[1:]

(28, 28, 3)

In [17]:
y = Conv2D(2, 2, activation='relu', input_shape=input_shape[1:])(x)
#y = Conv2D(2, 3, activation='relu', input_shape=input_shape[1:])(x)
#y = Conv2D(2, 4, activation='relu', input_shape=input_shape[1:])(x)
#y = Conv2D(2, [3,2], activation='relu', input_shape=input_shape[1:])(x)


In [18]:
y.shape

TensorShape([4, 27, 27, 2])

In [19]:
y[0].shape

TensorShape([27, 27, 2])

In [22]:
z = MaxPooling2D(pool_size=3, strides=3)(y)

In [23]:
z.shape

TensorShape([4, 9, 9, 2])

In [32]:
z[0].shape

TensorShape([9, 9, 2])

In [25]:
ab = Flatten()(z)

In [26]:
ab.shape

TensorShape([4, 162])

In [33]:
ab[0].shape

TensorShape([162])

In [34]:
abz = Dropout(0.5,  noise_shape=None, seed=10)(ab)

In [35]:
abz.shape

TensorShape([4, 162])

In [36]:
abz[0]

<tf.Tensor: shape=(162,), dtype=float32, numpy=
array([1.7712107 , 0.7304082 , 1.1002861 , 1.0997689 , 0.26944125,
       1.7799459 , 1.5348283 , 0.59914404, 0.82022333, 2.2225134 ,
       0.96761525, 1.4050715 , 1.3415996 , 1.1541085 , 1.6832244 ,
       3.9735637 , 1.327949  , 1.7339759 , 0.40360874, 1.6243153 ,
       1.3222866 , 1.7356225 , 1.5126362 , 1.1205052 , 1.5818596 ,
       2.099616  , 1.1131724 , 1.4485753 , 1.1854105 , 2.22932   ,
       1.4749444 , 1.4327649 , 1.9277661 , 0.86572564, 2.5057406 ,
       1.5053838 , 1.580573  , 0.6773782 , 2.503245  , 1.2981162 ,
       1.1211926 , 1.5723764 , 1.727878  , 1.8265392 , 1.8995774 ,
       1.897801  , 1.5444019 , 1.2882583 , 1.7044606 , 2.38668   ,
       1.5768151 , 1.2794065 , 1.031516  , 1.5175903 , 1.0218618 ,
       2.1919866 , 0.7011078 , 1.1545409 , 0.7817538 , 1.428085  ,
       1.3663881 , 1.5231884 , 0.955488  , 2.0923598 , 0.76004565,
       1.5698895 , 2.149169  , 1.5963371 , 0.43026096, 0.8003727 ,
       1.79956

In [37]:
final = Dense(10, activation='softmax')(abz)

In [38]:
final

<tf.Tensor: shape=(4, 10), dtype=float32, numpy=
array([[3.4117792e-03, 1.7351392e-01, 7.8409612e-03, 2.3536840e-02,
        5.2993689e-02, 1.9593398e-01, 5.3856433e-03, 2.5676662e-02,
        5.1045763e-01, 1.2487834e-03],
       [2.8876476e-03, 7.6466215e-01, 4.2982353e-03, 4.5445673e-03,
        3.4612428e-02, 6.2318849e-03, 8.0476478e-03, 4.3193433e-02,
        1.3111880e-01, 4.0326669e-04],
       [1.0946068e-02, 5.1653856e-01, 2.9053390e-02, 8.6412197e-03,
        2.7216414e-01, 4.8178941e-02, 3.9413483e-03, 2.5370806e-02,
        8.3355218e-02, 1.8103353e-03],
       [3.4006264e-03, 3.2728645e-01, 2.1387637e-02, 6.8157227e-03,
        3.3364972e-01, 5.2222896e-02, 3.4807620e-03, 1.0371729e-01,
        1.4774966e-01, 2.8928916e-04]], dtype=float32)>

In [39]:
final_relu = Dense(10, activation='relu')(abz)

In [40]:
final_relu

<tf.Tensor: shape=(4, 10), dtype=float32, numpy=
array([[0.0000000e+00, 0.0000000e+00, 4.0428340e-01, 8.1574269e-02,
        0.0000000e+00, 2.0807153e-03, 1.9278932e+00, 0.0000000e+00,
        5.3806698e-01, 6.6956854e-01],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 6.7480320e-01,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        6.2988675e-01, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 9.9203444e-01, 0.0000000e+00,
        0.0000000e+00, 2.6362417e+00, 0.0000000e+00, 0.0000000e+00,
        9.5421501e-02, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 4.0806589e-01, 5.5856061e-01, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00]], dtype=float32)>